module.exports = {
  TYPE_JWT_CREATE_UUID : 'TYPE_JWT_CREATE_UUID',
  TYPE_JWT_REFRESH_TOKEN : 'TYPE_JWT_REFRESH_TOKEN',
  TYPE_JWT_ACCESS_TOKEN : 'TYPE_JWT_ACCESS_TOKEN',
  TYPE_JWT_FIND_PASSWORD: 'TYPE_JWT_FIND_PASSWORD'
}